# Generated by Django 4.0.1 on 2022-03-14 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_founders_user_id_alter_investments_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='founders',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='investments',
            old_name='startup_id',
            new_name='startup',
        ),
        migrations.RenameField(
            model_name='investments',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='startups',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='uploads',
            old_name='startup_id',
            new_name='startup',
        ),
        migrations.AddField(
            model_name='founders',
            name='startup',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.startups'),
            preserve_default=False,
        ),
    ]
