# Generated by Django 4.0.1 on 2022-03-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_user_id_founders_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='startups',
            name='Address',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
