# Generated by Django 4.0.1 on 2022-03-14 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_startups_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='startups',
            old_name='Address',
            new_name='address',
        ),
    ]
