# Generated by Django 4.0.3 on 2022-03-15 11:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0009_users_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='UseUsers',
        ),
    ]
