# Generated by Django 4.0.3 on 2022-03-15 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_useusers_password_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useusers',
            name='email',
        ),
        migrations.RemoveField(
            model_name='useusers',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='useusers',
            name='role',
        ),
    ]
