# Generated by Django 4.0.3 on 2022-03-15 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_investments_user_alter_uploads_file'),
        ('myapp', '0012_remove_useusers_email_remove_useusers_icon_and_more'),
    ]

    operations = [
    ]
