# Generated by Django 4.0.3 on 2022-03-16 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_merge_20220315_1934'),
        ('myapp', '0013_merge_20220315_2100'),
    ]

    operations = [
    ]
