# Generated by Django 4.0.1 on 2022-03-16 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_merge_20220316_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useusers',
            name='contact_no',
            field=models.IntegerField(null=True),
        ),
    ]
